---
title: "bar"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{bar}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = c(7, 4)
)
```

```{r setup}
library(rg2)
df = jsonlite::fromJSON('
[{ "year": "1951", "value": 38 },
 { "year": "1952", "value": 52 },
 { "year": "1956", "value": 61 },
 { "year": "1957", "value": 145 },
 { "year": "1958", "value": 48 }]')
g2(df, g2_bar(),
   list(xField='value',
        yField='year',
        legend=list(position='top-left')))
```

###
```{r}
df = jsonlite::fromJSON(
  '
[  {
    "year": "1991",
    "value": 3,
    "type": "Lon"
  },
  {
    "year": "1992",
    "value": 4,
    "type": "Lon"
  },
  {
    "year": "1993",
    "value": 3.5,
    "type": "Lon"
  },
  {
    "year": "1994",
    "value": 5,
    "type": "Lon"
  },
  {
    "year": "1995",
    "value": 4.9,
    "type": "Lon"
  },
  {
    "year": "1996",
    "value": 6,
    "type": "Lon"
  },
  {
    "year": "1997",
    "value": 7,
    "type": "Lon"
  },
  {
    "year": "1998",
    "value": 9,
    "type": "Lon"
  },
  {
    "year": "1999",
    "value": 13,
    "type": "Lon"
  },
  {
    "year": "1991",
    "value": 6,
    "type": "Bor"
  },
  {
    "year": "1992",
    "value": 8,
    "type": "Bor"
  },
  {
    "year": "1993",
    "value": 2.5,
    "type": "Bor"
  },
  {
    "year": "1994",
    "value": 4,
    "type": "Bor"
  },
  {
    "year": "1995",
    "value": 6.9,
    "type": "Bor"
  },
  {
    "year": "1996",
    "value": 3,
    "type": "Bor"
  },
  {
    "year": "1997",
    "value": 9,
    "type": "Bor"
  },
  {
    "year": "1998",
    "value": 9,
    "type": "Bor"
  },
  {
    "year": "1999",
    "value": 24,
    "type": "Bor"
  }
]')
g2(
  df,
  'bar',
  list(
    isStack = T,
    xField = 'value',
    yField = 'year',
    seriesField = 'type',
    label = list(position = 'middle')
  )
)
g2(
  df,
  'bar',
  list(
    isGroup = T,
    xField = 'value',
    yField = 'year',
    seriesField = 'type',
    label = list(position = 'middle')
  )
)
g2(
  df,
  'bar',
  list(
    isStack = T,
    isPercent = T,
    xField = 'value',
    yField = 'year',
    seriesField = 'type',
    label = list(
      position = 'middle',
      content = htmlwidgets::JS('(v) => {return v.value.toFixed(2);}')
    )
  )
)
```

###
```{r}
df = jsonlite::fromJSON('[
  { "type": "分类一", "values": [76, 100] },
  { "type": "分类二", "values": [56, 108] },
  { "type": "分类三", "values": [38, 129] },
  { "type": "分类四", "values": [58, 155] },
  { "type": "分类五", "values": [45, 120] },
  { "type": "分类六", "values": [23, 99] },
  { "type": "分类七", "values": [18, 56] },
  { "type": "分类八", "values": [18, 34] }
]')

g2(df,
   'bar',
   list(
     xField = 'values',
     yField = 'type',
     isRange = T,
     label = list(position = 'middle',
                  layout = c(list(type = 'adjust-color')))
   ))
```


