---
title: "G2 official examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{G2 official examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include=FALSE}
library(rg2)
```

## Line

### Line Chart
```{r}
data = data.frame(year=1991:1999,value=c(3,4,3.5,5,4.9,6,7,9,13))

g2_view(data,
        encode('year','value'),
        children = list(g2_line(labels=list(list(text='value', style=list(dx=-10, dy=-12)))),
                        g2_point(style=list(fill='white'))))

g2_view(data,
        encode('year','value'),
        children = list(g2_line()+label(text='value', style=list(dx=-10, dy=-12)),
                        g2_point(style=list(fill='white'))))
```


## point

```{r}
url = 'https://gw.alipayobjects.com/os/basement_prod/6b4aa721-b039-49b9-99d8-540b3f87d339.json'

# Scatter plot
g2(url,encode('height', 'weight', color='gender')) + g2_point()
# One Dimension Scatter plot
g2(url,encode('height'), height = 50) + g2_point()

g2(url,encode(y='weight')) + g2_point()

```

```{r}
# Strip Plot
url = 'https://gw.alipayobjects.com/os/bmw-prod/2c813e2d-2276-40b9-a9af-cf0a0fb7e942.csv'
g2(url, encode('Cylinders','Horsepower',shape='line', size=20, color='Cylinders'),height=300) + 
  g2_point() +
  transform('sortX', channel='x') +
  coordinate(transform= list(list(type='transpose'))) +
  scale(x=list(type='point'),y=list(zero=TRUE), color=list(type='ordinal'))

g2(
  data = url,
  encode = encode('Cylinders', 'Horsepower', shape='line', size=20, color='Cylinders'),
  height=300
) +
transform(type='sortX', channel='x') +
coordinate(transform=list(list(type='transpose'))) +
g2_point() +
scale(x=list(type='point')) +
scale(y=list(zero=TRUE)) + 
scale(color=list(type='ordinal'))
```

## Bar
```{r}
mtcars |> tibble::rownames_to_column(var = 'model') |> g2(encode(y='mpg',x='model'))+g2_bar()
```

## Area
```{r}
data = list(
  type='fetch',
  value='https://assets.antv.antgroup.com/g2/range-spline-area.json',
  transform=list(list(type='map',callback=js('([x, low, high, v2, v3]) => ({ x, low, high, v2, v3 })')))
)
g2(data) + g2_area(encode('x', c('low','high')))
```

## Pie
```{r}
library(dplyr)
mtcars |>
  group_by(carb) |>
  summarise(n=n()) |> 
  mutate(carb=as.character(carb),percent=n/sum(n)) |>
  g2(encode(y='percent',color='carb')) +
  g2_pie() +
  label(position='outside',
        text=js('(data) => `${data.carb}: ${data.percent.toFixed(4) * 100}%`'))
```

multiple labels

```{r}
mtcars |>
  group_by(carb) |>
  summarise(n=n()) |> 
  mutate(carb=as.character(carb),percent=n/sum(n)) |>
  g2(encode(y='percent',color='carb')) +
  g2_pie() +
  label(text='carb') +
  label(text='n', style=list(dx=-10, dy=-12))
```


## Histogram
```{r}
g2('https://assets.antv.antgroup.com/g2/athletes.json',encode('weight', color='sex')) +
  g2_hist()+
  style(inset=0.25)

g2('https://assets.antv.antgroup.com/g2/athletes.json',encode('weight', color='sex')) +
  g2_rect()+
  transform(type='binX', y='count') +
  transform(type='stackY', orderBy='series') +
  style(inset=0.25)
```

## Component

### Legend
```{r}
g2('https://assets.antv.antgroup.com/g2/seattle-weather.json',
   encode(x=js('(d) => new Date(d.date).getUTCDate()'),
          y=js('(d) => new Date(d.date).getUTCMonth()'),
          color='temp_max'),
   height=360) +
  g2_cell(style=list(inset=0.5)) +
  transform(type='group', color='max') +
  scale(color=list(palette='rainbow')) +
  legend(color=list(position='bottom',
                    ribbonType='size',
                    indicator=TRUE,
                    title=FALSE,
                    tick=FALSE,
                    layout=list(justifyContent='center')
                    ))
```

### Label
```{r}
g2('https://assets.antv.antgroup.com/g2/aapl.json',
   encode(x=js('(d) => new Date(d.date)'),y='close')) +
  g2_line() +
  label(text='close',transform=list(list(type='overlapHide')))
```

### Scrollbar
```{r}
url = 'https://gw.alipayobjects.com/os/bmw-prod/551d80c6-a6be-4f3c-a82a-abd739e12977.csv'
g2(url, encode('date','close')) + g2_line() + scrollbar(x=list(),y=list(value=0.2))
```


## Animate

```{r}
data = 'https://gw.alipayobjects.com/os/bmw-prod/551d80c6-a6be-4f3c-a82a-abd739e12977.csv'
g2(data, encode('date','close')) +
    g2_line() + animate(enter = list(type='pathIn', duration=1000))
```

### waveIn
```{r}
library(dplyr)
mtcars |>
    group_by(carb) |>
    summarise(n=n()) |> 
    mutate(carb=as.character(carb),percent=n/sum(n)) |>
    g2(encode(y='percent',color='carb')) +
    g2_pie() +
    animate(enter=list(type='waveIn', duration=1000 ))
```

### ZoomIn
```{r}
g2('https://gw.alipayobjects.com/os/antvdemo/assets/data/bubble.json',
   encode('GDP', 'LifeExpectancy', color='continent', size='Population', shape='point')) +
  g2_point() +
  scale(size=list(range=c(4, 65)), y=list(domain=c(65, 90))) +
  style(fillOpacity=0.3,lineWidth=1) + 
  legend(size=FALSE) + 
  animate(enter = list(type='zoomIn', duration=1000))
```


## spaceLayer
```{r}
g2_space_layer(
  data='https://gw.alipayobjects.com/os/bmw-prod/fb9db6b7-23a5-4c23-bbef-c54a55fee580.csv',
  children = list(
    g2_col(encode('letter','frequency',color='letter'),
           transform=list(list(type='sortX',reverse=TRUE, by='y'))),
  g2_pie(encode(y='frequency',color='letter'),
         x=300,y=50,width=300,height=300,legend=FALSE))
  )
```

## spaceFlex
```{r}
g2_space_flex(
  data = 'https://assets.antv.antgroup.com/g2/seattle-weather.json',
  ratio = c(1, 2),
  direction = 'col',
  children = list(
    g2_col(encode(x=js('(d) => new Date(d.date).getUTCDate()'),
                  y='temp_max',
                  color='steelblue'),
                paddingBottom=0,
                paddingRight=300) +
    transform(type='groupX',y='max') +
    axis(x=FALSE),
    
    g2_space_flex(
      paddingBottom=60,
      ratio = c(2, 1),
      children = list(
        g2_cell(encode(x=js('(d) => new Date(d.date).getUTCDate()'),
                       y=js('(d) => new Date(d.date).getUTCMonth()'),
                       color='temp_max'),
                paddingBottom=60,
                paddingRight=0) + transform(type='group',color='max')+scale(color=list(palette='gnBu')) + style(inset=0.5) + axis(x=list(title='Date'),y=list(title='Month'))+legend(color=FALSE),
        g2_bar(encode(x=js('(d) => new Date(d.date).getUTCMonth()'),
                      y='temp_max',
                      color='steelblue')) +
          transform(type='groupX',y='max') +
          axis(x=FALSE)
      )
    )
  ),
  width=900
)
```

## repeatMatrix
```{r}
g2_repeat_matrix(
  data = list(
    type='fetch',
    value='https://assets.antv.antgroup.com/g2/weather.json',
    transform=list(list(
      type='map',
      callback=js('({ date, ...d }) => ({...d, date: new Date(date).getMonth() + ""})')
    ))
  ),
  encode(x='date', y=c('temp_max', 'precipitation', 'wind')),
  children = list(
    g2_line(encode(color='location')) + transform(type='groupX', y='mean') + scale(y=list(zero=TRUE))
  ),
  width = 300, height = 720
)
```

