---
title: "Line examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Line Examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rg2)
data(diamonds, package = 'ggplot2')
knitr::opts_chunk$set(
  comment = '', fig.width = 7.5, fig.height = 4
)
```

# line

### Basic line plot
```{r}
df = jsonlite::read_json("https://gw.alipayobjects.com/os/bmw-prod/1d565782-dde4-4bb6-8946-ea6a38ccf184.json",simplifyVector = T)

g2(df, 'line', list(
  xField = 'Date',
  yField = 'scales',
  xAxis = list(type = 'timeCat',
               tickCount = 5)
))
```
### Basic spline plot
```{r}
g2(df,
   'line',
   list(
     xField = 'Date',
     yField = 'scales',
     xAxis = list(type = 'timeCat',
                  tickCount = 5),
     smooth = TRUE
   ))
```
### point style
```{r}
g2(df,
   'line',
   list(
     xField = 'Date',
     yField = 'scales',
     label = list(),
     point = list(
       size=5,
       shape='diamond',
       style=list(
         fill='white',
         stroke='#5B8FF9',
         lineWidth=2
       )
     ),
     tooltip=list(showMarkers=F),
     state=list(
       active=list(
         style=list(
           shadowBlur=4,
           stroke='#000',
           fill='red'
         )
       )
     ),
     interactions=list(
       type='marker-active'
     ),
     xAxis = list(
       type = 'timeCat',
       tickCount = 5)
   ))
```
### line with slider
```{r}
g2(df,
   'line',
   list(
     xField = 'Date',
     yField = 'scales',
     xAxis = list(type = 'timeCat',
                  tickCount = 5),
     slider = list(start = 0.1,
                   end = 0.5)
   ))
```
### Line plot with dataMarker
```{r}
jsonlite::read_json(
  "https://gw.alipayobjects.com/os/antvdemo/assets/data/cpu-data.json",
  simplifyVector = T
) |>
  g2(
    g2_line(),
    list(
      xField = 'time',
      yField = 'cpu',
      seriesField = 'date',
      meta = list(cpu = list(
        time = list(type = 'cat'),
        max = 100,
        min = 0
      )),
      point=list(
        shape='breath-point'
      )
    )
  )
```

### Invert y-axis of line plot
```{r}
g2(df,
   'line',
   list(
     xField = 'Date',
     yField = 'scales',
     reflect = 'y',
     xAxis = list(
       type = 'timeCat',
       tickCount = 5,
       # because coordinate is reflect Y
       position = 'top'
     )
   ))
```

### multiple line
```{r}
jsonlite::fromJSON("https://gw.alipayobjects.com/os/bmw-prod/55424a73-7cb8-4f79-b60d-3ab627ac5698.json", simplifyVector = T) |> 
  g2(g2_line(),
     list(xField='year',
          yField='value',
          seriesField='category',
          xAxis=list(type='time'),
          yAxis=list(
            label = list(
              formatter=htmlwidgets::JS('(v) => `${v}`.replace(/\\d{1,3}(?=(\\d{3})+$)/g, (s) => `${s},`)'))
          )))
```


### Multiple line plot animation
```{r}
jsonlite::fromJSON('https://gw.alipayobjects.com/os/bmw-prod/e00d52f4-2fa6-47ee-a0d7-105dd95bde20.json', simplifyVector = T) |> 
  g2('line',
     list(
       xField='year',
       yField='gdp',
       seriesField='name',
       yAxis = list(
         label = list(
           formatter=htmlwidgets::JS('(v) => `${(v / 10e8).toFixed(1)} B`')
         )
       ),
       legend=list(position='top'),
       smooth=T,
       animation=list(
         appear=list(
           animation='path-in',
           duration=5000
         )
       )
     ))
```

### Line with area fill
```{r}
jsonlite::fromJSON('https://gw.alipayobjects.com/os/bmw-prod/e00d52f4-2fa6-47ee-a0d7-105dd95bde20.json', simplifyVector = T) |> 
  g2('line',
     list(
       xField='year',
       yField='gdp',
       seriesField='name',
       yAxis = list(
         label = list(
           formatter=htmlwidgets::JS('(v) => `${(v / 10e8).toFixed(1)} B`')
         )
       ),
       legend=list(position='top'),
       smooth=T,
       area = list(
         style=list(fillOpacity=0.15)
       ),
       animation=list(
         appear=list(
           animation='wave-in',
           duration=5000
         )
       )
     ))
```

### step line
```{r}
df = jsonlite::fromJSON('
[
  { "month": "Jan",  "key": "series1", "value": 125 },
  { "month": "Jan",  "key": "series2", "value": 51 },
  { "month": "Feb",  "key": "series1", "value": 132 },
  { "month": "Feb",  "key": "series2", "value": 91 },
  { "month": "Mar",  "key": "series1", "value": 141 },
  { "month": "Mar",  "key": "series2", "value": 34 },
  { "month": "Apr",  "key": "series1", "value": 158 },
  { "month": "Apr",  "key": "series2", "value": 47 },
  { "month": "May",  "key": "series1", "value": 133 },
  { "month": "May",  "key": "series2", "value": 63 },
  { "month": "June", "key": "series1", "value": 143 },
  { "month": "June", "key": "series2", "value": 58 },
  { "month": "July", "key": "series1", "value": 176 },
  { "month": "July", "key": "series2", "value": 56 },
  { "month": "Aug",  "key": "series1", "value": 194 },
  { "month": "Aug",  "key": "series2", "value": 77 },
  { "month": "Sep",  "key": "series1", "value": 115 },
  { "month": "Sep",  "key": "series2", "value": 99 },
  { "month": "Oct",  "key": "series1", "value": 134 },
  { "month": "Oct",  "key": "series2", "value": 106 },
  { "month": "Nov",  "key": "series1", "value": 110 },
  { "month": "Nov",  "key": "series2", "value": 88 },
  { "month": "Dec",  "key": "series1", "value": 91 },
  { "month": "Dec",  "key": "series2", "value": 56 }]')
g2(df,
   'line',
   list(xField='month', yField='value',seriesField='key',legend=F,stepType='hvh'))
```

