---
title: "example"
author: "13kay"
date: "2020/7/6"
output: html_document
---
```{r setup, include=FALSE}
library(dplyr)
library(rg2)
data("economics", package="ggplot2")
df = jsonlite::fromJSON('[
  { "region": "华东", "sales": 4684506.442 },
  { "region": "中南", "sales": 4137415.0929999948 },
  { "region": "东北", "sales": 2681567.469000001 },
  { "region": "华北", "sales": 2447301.017000004 },
  { "region": "西南", "sales": 1303124.508000002 },
  { "region": "西北", "sales": 815039.5959999998 }
]')
```


```{r}
g2TinyLine(economics,date,uempmed)
```

```{r}
g2TinyLine(economics,date,uempmed,color='#57CC99')
```


```{r}
g2TinyColumn(df, region, sales)
```

```{r}
g2TinyColumn(df, region, sales, color='#57CC99')
```


```{r}
g2Progress(0.75)
```

```{r}
g2RingProgress(0.9)
```

```{r}
data("economics", package="ggplot2")
data("economics_long", package="ggplot2")
g2Line(economics,date,uempmed)
```

```{r}
df = tibble(
  title = c('A','B','C','D'),
  measures = c(83,13,45,83),
  targets = c(90,90,90,90),
  ranges = rep(list(ranges = c(0,0.25,0.5,0.75,1)),4)
) %>% mutate_at(all_of(c('measures','targets','ranges')), as.list)
g2Bullet(df, 
         rangeMax = 100,
         cfg=list(title=list(visible=TRUE,text='Bullet chart'),
                  rangeColors=c('#F8DA41','#F3C173','#EE8C51','#E0605A')))
```


