#' G2 options
#'
#' Spec: \url{https://g2.antv.antgroup.com/en/spec/overview}
#'
#' @description
#'
#' G2 provides a Spec API which declares visualizations through a JavaScript object.
#'
#' Options of G2 is a named list:
#'
#' ```
#' {
#'   type: 'mark',  // view, spaceLayer, ...
#'   data: [],
#'   encode: {},
#'   scale: {},
#'   transform: [],
#'   coordinate: {},
#'   style: {},
#'   labelTransform: {},
#'   title: {},
#'   axis: {},
#'   legend: {},
#'   tooltip: {},
#'   scrollbar: {},
#'   slider: {},
#'   interaction: {},
#'   theme: {},
#' }
#' ```
#'
#' For the option with array value, you should use `list(list(...), list(...))`
#' to construct an array in JSON.
#' ```
#' transform()
#' ```
#' @md
#'
#' @param width optional default: 640
#' @param height optional default: 480
#' @param data required. Data Frame, URL of json/csv, for liquid data is a number, for gauge data is `list(value=list(target=200, total=400, percent=0.5,thresholds=c(...) name="score"))`
#'
#' @examples
#' g2_point(mtcars, 'drat', 'wt')
#'
#' @name opt
NULL




#' Spec
#'
#' G2 designed a spec to describe the visualizations that can be drawn, which
#' allows users to render charts by calling `chart.options(options)` with
#' specified options that meet the specification.
#'
#' @details
#'
#' ## Mark
#'
#' `g2_` family make marks
#'
#' ## Transform
#'
#' The Mark Transform in G2 offers a convenient method for transforming data and mark options, mainly used for analyzing data. The core of mark transform, which filters, modifies, aggregates and generates new channel values.
#'
#' Transform is an array, executed in the order when they are declared. It can be configured in mark:
#' ```R
#' g2_col(transform=list(list(type='stackY'), list(type='sortX')))
#' g2_col(transform=list(list(type='stackY')))
#' ```
#'
#' @md
#' @name spec
NULL



#' g2
#'
#' g2() create an G2 options
#'
#' @inherit opt
#' @param encode encode
#' @param type view/spaceLayer/spaceFlex/facetCircle/facetRect/repeatMatrix
#' @param ... Other arguments passed on to methods. Not currently used.
#'
#' @family g2
#' @export
#' @examples
#' g2_point(mtcars, 'drat', 'wt')
#'
g2 <- function(data, encode=NULL,  ..., width=640, height=480) {
  UseMethod('g2')
}

#' @details
#' param `type`:
#'  - view
#'  - spaceLayer
#'  - spaceFlex
#'  - facetCircle
#'  - facetRect
#'  - repeatMatrix
#'
#' @md
#' @export
g2.default <- function(data, encode=NULL, ...,
                       width=640, height=480) {
  data = if(is.character(data) && stringr::str_starts(data, 'http')) {
    list(type='fetch', value=data)
  } else if (inherits(data,'list')) {
    data
  } else if (is.data.frame(data)) {
    jsonlite::toJSON(data, auto_unbox = TRUE, null = 'null')
  } else {
    stop('data should be a data.frame, URL of json/csv or a list of G2 Data options')
  }

  # c()           => {}
  # list()        => []
  # c(1,2,3)      => [1,2,3]
  # list(x=1,y=2) => {"x": 1, "y": 2}
  opt = structure(
    list(
      data           = data,
      encode         = compact(encode),
      scale          = c(),
      transform      = list(),
      layout         = c(),
      coordinate     = c(),
      style          = c(),
      viewStyle      = c(),
      animate        = c(),
      state          = c(),
      label          = c(),
      title          = c(),
      axis           = c(),
      legend         = c(),
      tooltip        = c(),
      scrollbar      = c(),
      slider         = c(),
      interaction    = c(),
      theme          = c()
    ),
    class = c('g2')
  )

  x = list(opt=opt)
  htmlwidgets::createWidget(name='g2', x=x, width=width, height=height, package='rg2')
}


is.g2 <- function(x) inherits(x, 'g2')
is.g2mark <- function(x) inherits(x, 'g2mark')
is.g2transform <- function(x) inherits(x, 'g2transform')
is.g2label <- function(x) inherits(x, 'g2label')
is.g2animate <- function(x) inherits(x, 'g2animate')
is.g2spaceflex <- function(x) inherits(x, 'g2spaceflex')
is.widget <- function(x) inherits(x, 'htmlwidget')

#' Add components to a plot
#'
#' G2 options is named
#'
#'
#' @details
#' 1. if opt2.class is g2mark then append opt into opt1.children
#' 2. if opt1.type is spaceLayer or spaceFlex: check if opt2.encode exist
#' 3. if opt2.class is g2spec then modify opt1 with opt2 (spec in view or composite level)
#' 4. spec of mark will not use + operation, they configured in g2_xxx()
#' 5. the other option of view and composite are configured by `g2()`
#' 6. remove elements with null value and remove empty list
#'
#' @md
#'
#' @param opt1 result from `g2()` or  `+.g2`
#' @param opt2 opt generated by `g2_` family (g2mark) or other spec api (g2style, ...)
#'
#' @export
'+.g2' <- function(opt1, opt2) {
  opt = NULL
  if(is.widget(opt1)) opt=compact(opt1$x$opt) else opt=opt1

  # mark->children::array
  if (is.g2mark(opt2)) {
    opt = list_modify(opt, !!!opt2)
  }

  # transform::array
  else if (is.g2transform(opt2)) {
    if (pluck_exists(opt, 'transform')) {
      opt = list_modify(opt, transform = append(pluck(opt, 'transform'), opt2))
    } else {
      opt = list_merge(opt, transform = opt2)
    }
  }
  # label::array
  else if (is.g2label(opt2)) {
    if (pluck_exists(opt, 'labels')) {
      opt = list_modify(opt, labels = append(pluck(opt, 'labels'), opt2))
    } else {
      opt = list_merge(opt, labels = opt2)
    }
  }
  # animate::object
  else if (is.g2animate(opt2)) {
    opt = list_merge(opt, animate = opt2)
  } else {
    opt = list_modify(opt, !!!opt2)
  }

  if (is.widget(opt1)) {
    list_assign(opt1, x = list(opt=opt))
  } else {
    opt
  }

}


#' Encode
#'
#' encode can be configured either in mark or in view
#'
#' @details
#' For Bar charts, you will need to switch x and y encoding
#'
#' @md
#'
#' @param x encoding x
#' @param y encoding x
#' @param color encoding color
#' @param shape encoding shape
#' @export
encode <- function(x=NULL, y=NULL, ...) {
  discard_null(list_flatten(list(x=x, y=y, list(...))))
}




#' js
#'
#' export from htmlwidgets::JS
#'
#' @export
js <- htmlwidgets::JS
